# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20160716_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=10000, verbose_name='内容'),
        ),
    ]
