# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20160722_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_info',
            field=models.TextField(max_length=200, null=True, verbose_name='简介'),
        ),
    ]
